name: Deploy
on: [push]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup environment for root
        run: |
          echo "Current user: $(whoami)"
          echo "Hostanme: "$(hostname)""
          echo "Original PATH: $PATH"
          
          # Asegurar que kubectl esté disponible
          export PATH=$PATH:/usr/local/bin
          echo "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" >> $GITHUB_ENV
          
          # Configurar kubeconfig para root
          mkdir -p /root/.kube
          cp /etc/rancher/k3s/k3s.yaml /root/.kube/config
          chmod 600 /root/.kube/config
          echo "KUBECONFIG=/root/.kube/config" >> $GITHUB_ENV
          
      - name: Test kubectl
        run: |
          export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
          export KUBECONFIG=/root/.kube/config
          kubectl version --client
          kubectl get nodes
          
      - name: Deploy
        run: |
          export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
          export KUBECONFIG=/root/.kube/config
          kubectl apply -f your-deployment.yaml