name: 'Terraform IAC AWS Workflow'

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: [self-hosted, k3s, aws]
    environment: production

    defaults:
      run:
        shell: bash

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
      TERRAFORM_VERSION: "1.6.6"
        
    steps:
    - name: Aggressive Cleanup
      run: |
        echo "=== LIMPIEZA AGRESIVA DE ESPACIO ==="
        df -h
        
        # Limpiar caches del sistema
        sudo apt-get clean
        sudo apt-get autoclean
        sudo apt-get autoremove -y
        
        # Limpiar logs del sistema
        sudo journalctl --vacuum-time=1h
        sudo journalctl --vacuum-size=10M
        
        # Limpiar archivos temporales
        sudo find /tmp -type f -delete 2>/dev/null || true
        sudo find /var/tmp -type f -delete 2>/dev/null || true
        
        # Limpiar caches de Terraform de otros jobs
        sudo find / -name ".terraform" -type d -exec rm -rf {} + 2>/dev/null || true
        sudo find / -name "terraform.tfstate*" -type f -delete 2>/dev/null || true
        sudo find / -name "*.terraform*" -type f -delete 2>/dev/null || true
        
        # Limpiar Docker si está disponible
        docker system prune -af 2>/dev/null || true
        docker volume prune -f 2>/dev/null || true
        
        # Limpiar archivos de log grandes
        sudo find /var/log -name "*.log" -size +10M -delete 2>/dev/null || true
        sudo find /var/log -name "*.log.*" -delete 2>/dev/null || true
        
        # Limpiar caches de paquetes
        sudo rm -rf /var/cache/apt/archives/* 2>/dev/null || true
        sudo rm -rf /var/lib/apt/lists/* 2>/dev/null || true
        
        echo "=== Espacio después de limpieza agresiva ==="
        df -h
        
        # Verificar si tenemos al menos 1GB libre
        AVAILABLE=$(df / | awk 'NR==2 {print $4}')
        if [ $AVAILABLE -lt 1048576 ]; then
          echo "ERROR: Aún no hay suficiente espacio libre. Disponible: ${AVAILABLE}KB"
          echo "Se requieren al menos 1GB libres para continuar"
          exit 1
        fi

    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Terraformm
      run: |
        if command -v terraform &> /dev/null; then
          echo "Terraform ya está instalado: $(terraform version)"
          exit 0
        fi
        
        echo "Instalando Terraform ${TERRAFORM_VERSION}..."
        
        # Usar /usr/local/bin directamente
        cd /tmp
        curl -fsSL "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip" -o terraform.zip
        unzip -q terraform.zip
        sudo mv terraform /usr/local/bin/
        sudo chmod +x /usr/local/bin/terraform
        rm -f terraform.zip
        
        terraform version
        echo "Terraform instalado correctamente"

    - name: Terraform Init with Space Management
      working-directory: ${{ github.workspace }}
      run: |
        echo "=== Espacio antes de init ==="
        df -h
        
        # Limpiar cualquier cache previo en el directorio actual
        rm -rf .terraform* terraform.tfstate* 2>/dev/null || true
        
        # Configurar Terraform para usar menos espacio
        export TF_PLUGIN_CACHE_DIR="/tmp/terraform-plugin-cache"
        mkdir -p "$TF_PLUGIN_CACHE_DIR"
        
        echo "=== Inicializando Terraform con cache optimizado ==="
        terraform init -no-color -upgrade=false
        
        echo "=== Espacio después de init ==="
        df -h

    - name: Extract tfvars desde el commit
      id: extract_tfvars
      working-directory: ${{ github.workspace }}
      run: |
        TFVARS_FILE=$(echo "${COMMIT_MESSAGE}" | grep -o '\S*\.tfvars' || echo "")
        if [ -z "$TFVARS_FILE" ]; then
          echo "No se encontró archivo .tfvars en el mensaje del commit"
          echo "TFVARS_FILE=" >> $GITHUB_OUTPUT
        else
          echo "Archivo tfvars encontrado: $TFVARS_FILE"
          if [ -f "$TFVARS_FILE" ]; then
            echo "TFVARS_FILE=$TFVARS_FILE" >> $GITHUB_OUTPUT
          else
            echo "ADVERTENCIA: Archivo $TFVARS_FILE no existe"
            echo "TFVARS_FILE=" >> $GITHUB_OUTPUT
          fi
        fi

    - name: Terraform Format
      working-directory: ${{ github.workspace }}
      run: terraform fmt

    - name: Terraform Plan
      working-directory: ${{ github.workspace }}
      run: |
        echo "=== Espacio antes de plan ==="
        df -h
        
        if [ -n "${{ steps.extract_tfvars.outputs.TFVARS_FILE }}" ]; then
          terraform plan -input=false -var-file=${{ steps.extract_tfvars.outputs.TFVARS_FILE }}
        else
          terraform plan -input=false
        fi

    - name: Terraform Apply
      if: contains(github.event.head_commit.message, 'deploy') && !contains(github.event.head_commit.message, 'destroy')
      working-directory: ${{ github.workspace }}
      run: |
        echo "=== Espacio antes de apply ==="
        df -h
        
        if [ -n "${{ steps.extract_tfvars.outputs.TFVARS_FILE }}" ]; then
          terraform apply -auto-approve -var-file=${{ steps.extract_tfvars.outputs.TFVARS_FILE }}
        else
          terraform apply -auto-approve
        fi

    - name: Terraform Destroy
      if: contains(github.event.head_commit.message, 'destroy') && !contains(github.event.head_commit.message, 'deploy')
      working-directory: ${{ github.workspace }}
      run: |
        if [ -n "${{ steps.extract_tfvars.outputs.TFVARS_FILE }}" ]; then
          terraform destroy -auto-approve -var-file=${{ steps.extract_tfvars.outputs.TFVARS_FILE }}
        else
          terraform destroy -auto-approve
        fi

    - name: Final Cleanuppd
      if: always()
      run: |
        echo "=== Limpieza final ==="
        # Limpiar cache de plugins de Terraform
        rm -rf /tmp/terraform-plugin-cache 2>/dev/null || true
        rm -rf .terraform* 2>/dev/null || true
        # Limpiar archivos temporales
        sudo find /tmp -name "*terraform*" -delete 2>/dev/null || true
        df -h