name: 'Terraform IAC AWS Workflow'

on:
  push:
    branches: [ "main" ]
  
  workflow_dispatch:


permissions:
  contents: read
  


jobs:
  terraform:
    name: 'Terraform'
    runs-on: [self-hosted, k3s, aws]  # ← CAMBIO AQUÍd
    environment: production

    defaults:
      run:
        shell: bash

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        
    steps:
    # Bajamos el codigo del repo al runner
    - name: Checkout
      uses: actions/checkout@v4


    # Instalamos Terraform en el runner
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    # Inicializar Terraforms
    - name: Terraform Init
      run: |
        echo "=== Verificando espacio ==="
        df -h
        
        echo "=== Limpiando cache previo ==="
        rm -rf .terraform* terraform.tfstate* 2>/dev/null || true
        
        echo "=== Liberando espacio en /tmp ==="
        find /tmp -name "*terraform*" -type f -delete 2>/dev/null || true
        find /tmp -name ".terraform*" -type d -exec rm -rf {} + 2>/dev/null || true
        
        echo "=== Espacio después de limpiar ==="
        df -h
        
        echo "=== Inicializando Terraform ==="
        terraform init -no-color

    - name: Extract tfvars desde el commit
      id: extract_tfvars
      run: |
        TFVARS_FILE=$(echo "${COMMIT_MESSAGE}" | grep -o '\S*\.tfvars')
        echo "TFVARS_FILE=$TFVARS_FILE" >> $GITHUB_OUTPUT

        
    # Formatear codigo
    - name: Terraform Format
      run: terraform fmt

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan -input=false -var-file=${{ steps.extract_tfvars.outputs.TFVARS_FILE }}

    # Apply the Terraform plan
    - name: Terraform Apply
      if: contains(github.event.head_commit.message, 'deploy') && !contains(github.event.head_commit.message, 'destroy')
      run: terraform apply -auto-approve -var-file=${{ steps.extract_tfvars.outputs.TFVARS_FILE }}

    # Destroy the Terraform-managed infrastructure
    - name: Terraform Destroy
      if: contains(github.event.head_commit.message, 'destroy') && !contains(github.event.head_commit.message, 'deploy')
      run: terraform destroy -auto-approve -var-file=${{ steps.extract_tfvars.outputs.TFVARS_FILE }}